name: Publish Package

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to publish (e.g., 1.0.0, 1.0.0-beta.1)'
        required: true
      tag:
        description: 'NPM tag (latest, beta, next)'
        required: false
        default: 'latest'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Get version from tag
        if: startsWith(github.ref, 'refs/tags/')
        id: tag_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Update package version
        if: github.event_name == 'workflow_dispatch' || startsWith(github.ref, 'refs/tags/')
        run: |
          VERSION=${{ github.event.inputs.version || steps.tag_version.outputs.VERSION }}
          CURRENT_VERSION=$(node -p "require('./package.json').version")
          if [ "$VERSION" != "$CURRENT_VERSION" ]; then
            npm version $VERSION --no-git-tag-version
          else
            echo "Version already set to $VERSION"
          fi

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run lint

      - name: Build
        run: npm run build

      - name: Publish to npm
        run: |
          TAG=${{ github.event.inputs.tag || (contains(steps.tag_version.outputs.VERSION, '-') && 'beta' || 'latest') }}
          npm publish --tag $TAG
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create GitHub Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: ${{ contains(steps.tag_version.outputs.VERSION, '-') }}